TrailheadProject/src/objects/Challenge__c.object
<CustomObject>
    <fields>
        <fullName>Final_Date__c</fullName>
        <label>Final Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrailheadProject/src/objects/Challenge_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Challenge_Name__c</fullName>
        <label>Challenge Name</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Challenge Participants</relationshipLabel>
        <relationshipName>InternToChallenge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intern_Name__c</fullName>
        <label>Intern Name</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipLabel>Challenge Participants</relationshipLabel>
        <relationshipName>ChallengeToIntern</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Challenge Participant</label>
    <nameField>
        <displayFormat>Participant-{0}</displayFormat>
        <label>Challenge Participant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenge Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrailheadProject/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>trailheadId__c</fullName>
        <label>trailheadId</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrailheadProject/src/classes/TrailheadDataHandlerTest.cls
@isTest
public class TrailheadDataHandlerTest {
	
	@isTest
	static void getInternsDataTest(){
		List<String> internsIds = new List<String>();
		internsIds.add('005500000060WgXAAU');
		internsIds.add('005500000060WKbAAM');
		internsIds.add('005500000060XEjAAM');
		
		Date fd = Date.newInstance(2016, 8, 25);
		Challenge__c newChallenge = new Challenge__c(Name = 'test', Final_Date__c = fd);
		insert newChallenge;
		
		List<Intern__c> listInterns = new List<Intern__c>();
		listInterns.add(new Intern__c(Name = 'intern1', trailheadId__c = '005500000060WgXAAU'));
		listInterns.add(new Intern__c(Name = 'intern2', trailheadId__c = '005500000060WKbAAM'));
		listInterns.add(new Intern__c(Name = 'intern3', trailheadId__c = '005500000060XEjAAM'));
		insert listInterns;
		
		List<Challenge_Participant__c> junc = new List<Challenge_Participant__c>();
		
		for(Intern__c intern : listInterns){
			junc.add(new Challenge_Participant__c(Challenge_Name__c = newChallenge.Id, Intern_Name__c = intern.Id));	
		}

		insert junc;

		TrailheadDataHandler handler = new TrailheadDataHandler();
        
		Test.setMock(HttpCalloutMock.class, new CalloutMock());

		Test.startTest();
			handler.getInternsData(internsIds);
		Test.stopTest();

		System.assertEquals(true, true);
		
	}
	

 }