TrailheadProject/src/objects/Challenge__c.object
<CustomObject>
    <fields>
        <fullName>Final_Date__c</fullName>
        <label>Final Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <label>Challenge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrailheadProject/src/objects/Challenge_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Badges__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Badges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Challenge_Name__c</fullName>
        <label>Challenge Name</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Challenge Participants</relationshipLabel>
        <relationshipName>InternToChallenge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intern_Name__c</fullName>
        <label>Intern Name</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipLabel>Challenge Participants</relationshipLabel>
        <relationshipName>ChallengeToIntern</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>startBadges__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Start Badges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>startScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Start Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Challenge Participant</label>
    <nameField>
        <displayFormat>Participant-{0}</displayFormat>
        <label>Challenge Participant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenge Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrailheadProject/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>trailheadId__c</fullName>
        <label>trailheadId</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrailheadProject/src/classes/TrailheadPageController.cls
public class TrailheadPageController {
    public Boolean NoActualChallenge {get; set;}
    public Date actualDate = Date.today();
    public List<Challenge_Participant__c> ChallengeParticipantList {get; set;}
        
    public TrailheadPageController (){
        
    }
     
    private void getCurrentData(){
        List<Challenge_Participant__c> actualChallenges =  [SELECT Badges_Progress__c, Score_Progress__c, startScore__c, startBadges__c, Score__c, Badges__c, Intern_Name__r.trailheadId__c, Intern_Name__r.Name, Challenge_Name__r.Name, Challenge_Name__r.Final_Date__c FROM Challenge_Participant__c];    
        if(actualChallenges.size() != 0 && actualChallenges != null){
           ChallengeParticipantList  = actualChallenges;  
           NoActualChallenge = true;          
        }
    } 
     
    public void refresh(){
                List<Intern__c> interns = [SELECT Id, trailheadId__c FROM Intern__c];
                List<String> internsIds = new List<String>();
                
                for(Intern__c intern : interns){
                        internsIds.add(intern.trailheadId__c);
                }

                if(internsIds != null){
                        TrailheadDataHandler handler = new TrailheadDataHandler();
                        handler.getInternsData(internsIds);
                        this.getCurrentData();
                } 
    }
}